gamemart/urls.py
"""Gamemart URL Configuration"""
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout_then_login
from gameapp import views

urlpatterns = [
    url(r'^$', views.home, name='home_page'),

    # Authentication related urls
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', lambda request: logout_then_login(request, "/"), name='logout'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # Registration related urls
    url(r'^register/$', views.register, name='register'),
    # url(r'^oauth/', include('social_django.urls', namespace='social')), # TODO: fix issue on production server

    # User dashboard related urls
    url(r'^accounts/profile/$', views.home),
    url(r'^account/dashboard/$', views.dashboard, name='user_dashboard'),
    url(r'^account/editProfile/$', views.editProfile, name='editProfile'),
    url(r'^changeFirstName/$', views.changeFirstName),
    url(r'^changeLastName/$', views.changeLastName),
    url(r'^changeEmail/$', views.changeEmail),
    url(r'^changeBio/$', views.changeBio),

    # Games related urls
    url(r'^games/$', views.browse, name='browse'),
    url(r'^games/(?P<type>[-\w]+)/$', views.explore, name='explore'),
    url(r'^games/category/(?P<tag>[-\w]+)/$', views.explore_by_taxonomy, name='browse_by_category'),
    url(r'^games/tag/(?P<tag>[-\w]+)/$', views.explore_by_taxonomy, name='browse_by_tag'), # TODO: implement tag field on submit form
    url(r'^search/$', views.search, name='search'),
    url(r'^game/(?P<slug>[-\w]+)/$', views.game_by_slug, name='game'),
    url(r'^payment/(?P<status>[-\w]+)/on/(?P<slug>[-\w]+)/$', views.payment, name='pay'),

    # Developer related urls
    url(r'^developer/$', views.developer, name='developer'),
    url(r'^submit/$', views.submit, name='submit'),
    url(r'^api/(?P<target>[-\w]+)/$', views.api),
    url(r'^user/(?P<slug>[-\w]+)/$', views.game_by_slug, name='user_view'),
    url(r'^game/edit/([0-9]+)/$', views.edit_game, name='edit_game'),
    url(r'^game/delete/([0-9]+)/$', views.del_game, name='del_game'),

    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gameapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import JSONField

class Taxonomy(models.Model):
    taxonomy_type   = models.CharField(max_length=20)
    label           = models.CharField(max_length=50)
    slug            = models.SlugField(max_length=50)
    parent          = models.ForeignKey('self',null=True,blank=True)

    def __str__(self):
        return u'%s' % (self.label)

class Review(models.Model):
    game            = models.ForeignKey('Game')
    person          = models.ForeignKey('User')
    rating          = models.IntegerField()
    review          = models.TextField()

    def __str__(self):
        return u'review by %s on %s' % (self.person, self.game)

class User(AbstractUser):
    slug            = models.SlugField(max_length=100, unique=True)
    pic             = models.ForeignKey('Asset', null=True, blank=True)
    bio             = models.TextField(null=True, blank=True)
    register_date   = models.DateTimeField(auto_now=True,null=True, blank=True)
    user_type       = models.CharField(max_length=10,default='player') #user_type values are player, developer and admin
    is_validated    = models.BooleanField(default=False)

    def __str__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class Game(models.Model):
    owner           = models.ForeignKey('User')
    title           = models.CharField(max_length=100)
    slug            = models.SlugField(max_length=100, unique=True)
    desc            = models.TextField(blank=True)
    instruction     = models.TextField(blank=True)
    url             = models.URLField()
    price           = models.FloatField()
    added_date      = models.DateTimeField(auto_now=True)
    is_featured     = models.BooleanField(default=False)
    taxonomies      = models.ManyToManyField('Taxonomy')

    def __str__(self):
        return u'%s' % (self.title)

class Asset(models.Model):
    asset_type      = models.CharField(max_length=50)
    url             = models.FileField()
    game            = models.ForeignKey('Game', null=True, on_delete=models.CASCADE)

class Gameplay(models.Model):
    player          = models.ForeignKey('User', on_delete=models.CASCADE)
    game            = models.ForeignKey('Game', on_delete=models.CASCADE)
    score           = models.FloatField(default=0, null=True, blank=True)
    state           = models.TextField(null=True, blank=True)
    timestamp       = models.DateTimeField(auto_now=True)

class Purchase(models.Model):
    buyer           = models.ForeignKey('User', on_delete=models.CASCADE)
    game            = models.ForeignKey('Game', on_delete=models.CASCADE)
    date            = models.DateTimeField(auto_now=True)
    amount          = models.FloatField()
    status          = models.CharField(max_length=50, default='error')

gameapp/forms.py
import itertools

from django import forms
#from django.contrib.auth.models import User
from django.utils.text import slugify
from gameapp.models import User, Game, Taxonomy
from django.utils import timezone


class UserForm(forms.ModelForm):
    """Handle user registration form."""

    # Use password widget so password isn't shown
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'password', 'email', 'user_type')

    def save(self):
        instance = super(UserForm, self).save(commit=False)

        instance.slug = orig = '-'.join((slugify(instance.first_name), slugify(instance.last_name)))

        # If the slug already exist, append it with the next iterating number
        for x in itertools.count(1):
            if not User.objects.filter(slug=instance.slug).exists():
                break
            instance.slug = '%s-%d' % (orig, x)

        instance.save()

        return instance


class FirstNameForm(forms.Form):
    first_name = forms.CharField(max_length=30)

class LastNameForm(forms.Form):
    last_name = forms.CharField(max_length=30)

class EmailForm(forms.Form):
    email = forms.EmailField()

class BioForm(forms.Form):
    bio = forms.CharField(max_length=1000)

class SubmitForm(forms.ModelForm):
    """Handle game submission form."""

    class Meta:
        model = Game # Referencing the Game model and its fields
        fields = ['title', 'desc', 'instruction', 'url', 'price']

    # Additional fields
    categories = forms.ModelMultipleChoiceField(Taxonomy.objects.filter(taxonomy_type='game_category'))
    image = forms.FileField()

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(SubmitForm, self).__init__(*args, **kwargs)

    def save(self, request):
        instance = super(SubmitForm, self).save(commit=False)

        instance.owner_id = request.user.id
        instance.added_date = timezone.now()
        instance.slug = orig = slugify(instance.title)

        # If the slug already exist, append it with the next iterating number
        for x in itertools.count(1):
            if not Game.objects.filter(slug=instance.slug).exists():
                break
            instance.slug = '%s-%d' % (orig, x)

        instance.save()

        return instance

gameapp/templates/base_without_jumbotron.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include "head.html" %}
    {% block head_script %}{% endblock %}
    {% block head_meta %}{% endblock %}
    <title>{% block title %}Exercise template{% endblock %}</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
  </head>
  <body>
    <!-- Load Facebook SDK for JavaScript -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <script>window.twttr = (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0],
        t = window.twttr || {};
      if (d.getElementById(id)) return t;
      js = d.createElement(s);
      js.id = id;
      js.src = "https://platform.twitter.com/widgets.js";
      fjs.parentNode.insertBefore(js, fjs);

      t._e = [];
      t.ready = function(f) {
        t._e.push(f);
      };

      return t;
    }(document, "script", "twitter-wjs"));</script>

    {% include "nav.html" %} <!--nav bar included -->

    <!--Success and Error message-->
    {% if messages %}
    <div class="container">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ message|safe }}
      </div>
      {% endfor %}
    </div>
    {% endif %}


    {% block content %}
    <div class="starter-template">
      <h1>Bootstrap starter template</h1>
      <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
    </div>
    {% endblock %}

    {% include "footer.html" %}

    {% block footer_script %}
    {% endblock %}
  </body>
</html>

gameapp/templates/browse.html
{% extends "base.html" %}
{% block title %}Browse games{% endblock %}
{% block content %}
{% load static %}


<div class="container">
  {% if games %}
    <div id="products" class="row">
      {% for game in games %}
        <div class="item col-xs-12 col-sm-4 col-lg-4">
          <div class="thumbnail">
            <img class="group list-group-image" src="{{ game.banner_url }}" alt="no image" />
            <div class="caption">
              <h4 class="group inner list-group-item-heading"><a href="{{BASE_URL}}/game/{{ game.slug }}">{{ game.title }}</a></h4>
              {# <p class="group inner list-group-item-text">{{game.desc|truncatechars:100}}</p>#} <!-- game description minimized-->
              {% if not game.bought and game.price != 0 %}
                <div class="row">
                  <div class="col-xs-12 col-sm-6">
                    <p class="lead">€ {{ game.price }}</p> <!--retrieving game price-->
                  </div>
                  <div class="col-xs-12 col-sm-6 text-right">
                    {% include "buy_form.html" with next_purchase_id=next_purchase_id checksum=game.checksum %}
                  </div>
                </div>
              {% else %}
                <div class="row">
                  <div class="col-xs-12 col-sm-6"></div>
                  <div class="col-xs-12 col-sm-6 text-right">
                    <a class="btn btn-success" href="{{BASE_URL}}/game/{{ game.slug }}">Play</a>
                  </div>
                </div>
              {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
    {% include "games_pagination.html" %}
  {% else %}
    <div class="well well-lg">Too bad we have no {{page_title}} yet </div> <!--game page dispay-->
  {% endif %}
</div>


{% endblock %}

gameapp/templates/buy_form.html
{% if not userIsLoggedIn %}
<a href="{% url 'login' %}" class="btn btn-primary">Buy</a>
{% elif not game_bought and game.price != 0   %}
<form action="http://payments.webcourse.niksula.hut.fi/pay/" method="POST">
  <input type="hidden" name="pid" value="{{next_purchase_id}}" />
  <input type="hidden" name="sid" value="GameMartInc" />
  <input type="hidden" name="success_url" value="{{BASE_URL}}{% url 'pay' 'success' game.slug %}" />
  <input type="hidden" name="cancel_url" value="{{BASE_URL}}{% url 'pay' 'canceled' game.slug %}" />
  <input type="hidden" name="error_url" value="{{BASE_URL}}{% url 'pay' 'error' game.slug %}" />
  <input type="hidden" name="checksum" value="{{ checksum }}" />
  <input type="hidden" id="id_amount" name="amount" value="{{ game.price }}" />
    <input class="btn btn-primary" type="submit" value="Buy">
</form>
{% endif %}

gameapp/templates/developer.html
{% extends "base.html" %}
{% block title %}Developer Dashboard{% endblock %}
{% block head_script %}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" >
{% endblock %}
{% block footer_script %}
<script src="//cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js" ></script>
<script>
$(document).ready(function(){
  $('#gameTable').DataTable();
});
</script>
{% endblock %}
{% block content %}
{% load static %}

<div class="container">
  <div class="row">
    <div class="col-md-9 col-sm-12 col-xs-12">
      {% if games %}
      <h2>Your Games</h2>
      <table class="table" id="gameTable">
        <thead>
        <tr>
          <th>Title</th>
          <th>Price</th>
          <th>Game Income</th>
          <th>Is Featured?</th>
          <th>Added date</th>
          <th>Buyer</th>
          <th>Play Count</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for game in games %}
        <tr>
          <td><a href="{% url 'game' game.slug %}">{{ game.title }}</a></td>
          <td class="text-right">€ {{ game.price }}</td>
          <td class="text-right">€ {{ game.income }}</td>
          <td class="text-center">
            {% if game.featured %}
              <img src="{% static '/admin/img/icon-yes.svg' %}" alt="yes" />
            {% else %}
              <img src="{% static '/admin/img/icon-no.svg' %}" alt="no" />
            {% endif %}
          </td>
          <td>{{ game.added_date }}</td> <!--date the game was added-->
          <td>{{ game.purchase_count }}</td> <!--number of purchase-->
          <td>{{ game.play_count }}</td> <!--number of times game has been played-->
          <td><a href="{% url 'edit_game' game.id %}">Edit</a></td>
          <td><a href="{% url 'del_game' game.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
      {% else %}
        <div class="well well-lg">You have no game yet. <a href="{% url 'submit' %}" class="btn btn-primary pull-right">Submit your first game</a></div>
      {% endif %}
      <h2>Your Sales</h2>
      {% if sales %}
      <table class="table">
        <tr>
          <th>Game</th>
          <th>Buyer</th>
          <th>Bought Date</th>
          <th>Amount</th>
        </tr>
        {% for sale in sales %}
        <tr>
          <td><a href="{% url 'game' sale.game_slug %}">{{ sale.game_title }}</a></td> <!--display game title-->
          <td>{{ sale.buyer_name }}</td> <!--buyer's name-->
          <td>{{ sale.bought_date }}</td>   <!--date of purchase-->
          <td class="text-right">€ {{ sale.amount }}</td>
        </tr>
        {% endfor %}
        
        <!--STATS-->
        <!--Total income generated for developer-->
        <tr>
          <th colspan="3">Total Income</th>
          <th class="text-right">€ {{ total_income }}</th>
        </tr>
      </table>
      {% else %}
        <div class="well well-lg">You have no sale yet</div>
      {% endif %}
    </div>
    <div class="col-md-3 col-sm-12 col-xs-12">
      <div class="list-group">
        <a href="#" class="list-group-item visitor">
            <h3 class="pull-right">
                <i class="fa fa-gamepad"></i>
            </h3>
            <h4 class="list-group-item-heading count">
                {{ total_game }}</h4>
            <p class="list-group-item-text">
                Number of games</p>
        </a>
        <a href="#" class="list-group-item">
            <h3 class="pull-right">
                <i class="fa fa-money"></i>
            </h3>
            <h4 class="list-group-item-heading count">
                € {{ total_income }}</h4>
            <p class="list-group-item-text">
                Total Earning</p>
        </a>
        <a href="#" class="list-group-item">
            <h3 class="pull-right">
                <i class="fa fa-users"></i>
            </h3>
            <h4 class="list-group-item-heading count">
                {{ total_buyer }}</h4>
            <p class="list-group-item-text">
                Number of Subscribers</p>
        </a>
        <a href="#" class="list-group-item">
            <h3 class="pull-right">
                <i class="fa fa-play-circle-o"></i>
            </h3>
            <h4 class="list-group-item-heading count">
                {{ total_play }}</h4>
            <p class="list-group-item-text">
                Total Play Count</p>
        </a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

gameapp/templates/edit_game.html
{% extends "base.html" %}
{% block title %}Submit Games{% endblock %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
      <form id="submitgamesform" method="post" enctype="multipart/form-data">{% csrf_token %}
          {% for field in form %}
              {% if field.errors %}
                  <div class="control-group error form-group">
                      <label class="control-label">{{ field.label }}</label> <!--insert label-->
                      <div class="">{{ field }}
                          <span class="help-inline">
                              {% for error in  field.errors %}{{ error }}{% endfor %} <!--handling errors-->
                          </span>
                      </div>
                  </div>
              {% else %}
                  <div class="form-group">
                      <label class="control-label">{{ field.label }}</label>
                      <div class="">{{ field }}
                          {% if field.help_text %}
                              <p class="help-inline"><small>{{ field.help_text }}</small></p>
                          {% endif %}
                      </div>
                  </div>
              {% endif %}
          {% endfor %}
        <div class="form-actions">
          <button type="submit" class="btn btn-primary" >Update</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- -->
{% endblock %}

gameapp/templates/footer.html
{% load static %}
<footer class="footer">
  
  <!--/.footer-->

  <div class="footer-bottom">
      <div class="container">
          <p class="pull-left"> Copyright © GameMart 2017. All right reserved. </p>
          <div class="pull-right">
              <ul class="nav nav-pills payments">
                <li><i class="fa fa-cc-visa"></i></li>
                  <li><i class="fa fa-cc-mastercard"></i></li>
                  <li><i class="fa fa-cc-amex"></i></li>
                  <li><i class="fa fa-cc-paypal"></i></li>
              </ul>
          </div>
      </div>
  </div>
  <!--/.footer-bottom-->
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{% static 'gameapp/js/jquery.min.js' %}"><\/script>')</script>
<!-- Latest compiled and minified JavaScript -->
<script src="{% static 'gameapp/js/bootstrap.min.js' %}" ></script>
<script src="{% static 'gameapp/js/main.js' %}" ></script>

gameapp/templates/gameview.html
{% extends "base_without_jumbotron.html" %}
{% block title %}{{ game.title }}{% endblock %}
{% block head_meta %}
<meta property="og:url"           content="{% url 'game' game.slug %}" />
<meta property="og:type"          content="website" />
<meta property="og:title"         content="{{ game.title }}" />
<meta property="og:description"   content="{{ game.desc }}" />
<meta property="og:image"         content="{{ game_banner_url }}" />
{% endblock %}
{% block content %}

<!--game view for purchased games-->
<div class="container">
  {% if game_bought or game.price == 0  %}
    <div class="row">
      <div class="col-md-12">
        <iframe id="gameframe" width="100%" height="100%" src="{{ game.url }}" data-gameid="{{game.id}}"></iframe>
      </div>
    </div>
  {% endif %}

  <div class="row">
    <div class="col-md-10">
      <h1>{{ game.title }}</h1> <!--displays game title-->
    </div>
    <div class="col-md-2">

    </div>
  </div>


  <!-- Game image/ title-->
  <div class="row">
    <div class="col-md-8">
      {% if game_banner_url != 'none' %}
        <img class="game-banner image-responsive" src="{{ game_banner_url }}" alt="{{ game.title }}" />
      {% endif %}
      <p>{{ game.desc }}</p>
      {% if userIsLoggedIn and game.instruction %}
        <h2>Instruction</h2>
        <p>{{ game.instruction }}</p>
      {% endif %}
    </div>

    <div class="col-md-4 ">
      <div class="row">
        <div class="col-md-6 pricetag"><h3>€ {{ game.price }}</h3></div> <!--displays game price-->
        <div class="col-md-6 text-right">{% include "buy_form.html" %}</div> <!--links to buy page-->
      </div>

      <hr />

      <div class="list-group">
        <a href="#" class="list-group-item visitor">
            <h3 class="pull-right">
                <i class="fa fa-gamepad"></i>
            </h3>
            <h4 class="list-group-item-heading count">
                {{ play_count }}</h4>
            <p class="list-group-item-text">
                Times played</p>
        </a>
        <a href="#" class="list-group-item google-plus">
            <h3 class="pull-right">
                <i class="fa fa-users"></i>
            </h3>
            <h4 class="list-group-item-heading count">
                {{ purchase_count }}</h4>
            <p class="list-group-item-text">
                Subscribers</p>
        </a>
      </div>

      <!-- Displaying high scores-->
      {% if highscore|length > 0 %}
        <hr/>
        <h4>Highscore</h4>
        <table class="table">
          <tr>
            <th>Username</th>
            <th>Score</th>
          </tr>
          {% for key, score in highscore %}
            <tr>
              <td>{{key}}</td>
              <td>{{score}}</td>
            </tr>
          {% endfor %}
        </table>
      {% endif %}
      <hr />
      <div class="fb-like"
        data-href="{{ BASE_URL}}{% url 'game' game.slug %}"
        data-width="290"
        data-layout="standard"
        data-action="like"
        data-show-faces="false">
      </div>
      <br/><br/>
      <a class="twitter-share-button" href="{{ BASE_URL}}{% url 'game' game.slug %}">Tweet</a>
    </div>
  </div>
</div>



{% endblock %}

gameapp/templates/payment.html
{% extends "base_without_jumbotron.html" %}
{% block title %}Game purchase{% endblock %}
{% block content %}
{% load static %}

<!--Successful payment-->
<div class="container">
  {% if status == "success" %} <!-- access game when payment successful-->
    <h1 class="text-success">Thank You! :)</h1>
    <p>Your game is ready to be played now</p>
    <a href="{% url 'game' game.slug %}">Play {{ game.title }} now!</a>

  {% elif status == "canceled" %}
    <h1 class="text-success">Oh snap! :)</h1>
    <p>Maybe you want to buy another game instead?</p>
    <a href="{% url 'browse' %}">Browse games</a>
    
  {% elif status == "error" %}
    <h1 class="text-success">Ooops! :)</h1>
    <p>Something is wrong, please try again</p>
  {% endif %}
</div>



{% endblock %}

gameapp/templates/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}


<!-- Registration form for players-->

<div class="container">
  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">

    <form action="/register/" method="post"> <!--form-->
     {% csrf_token %}
     <p class="form-group">
       <label for="id_first_name">First name:</label>
       <input class="form-control" id="id_first_name" type="text" name="first_name"/>
     </p>

     <p class="form-group">
       <label for="id_last_name">Last name:</label>
       <input class="form-control" id="id_last_name" type="text" name="last_name"/>
     </p>

     <p class="form-group">
       <label for="id_username">Username:</label>
       <input class="form-control" id="id_username" type="text" name="username"/>
     </p>

     <p class="form-group">
       <label for="id_password">Password:</label>
       <input class="form-control" id="id_password" type="password" name="password" required=""/>
     </p>

     <p class="form-group">
       <label for="id_email">Email:</label>
       <input class="form-control" id="id_email" type="email" name="email" required="" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,63}$"/>
     </p>

       <div class="radio">
          <label>
            <input type="radio" name="user_type" id="optionsRadios1" value="player" checked>
            Register as player (you can buy and play games)
          </label>
        </div>
        <div class="radio">
          <label>
            <input type="radio" name="user_type" id="optionsRadios2" value="developer">
            Register as developer (you can submit and manage games)
          </label>
        </div>

        <br/>

        <input class="form-control btn btn-primary" type="submit" value="Register" />

      </form> <!--form-->

    </div>
  </div>
</div>
{% endblock %}

gameapp/templates/registerAdmin.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}

<div class="container">
   <h2>Admin Registration</h2>

     <form action="/register/" method="post">
     {% csrf_token %}
     <p>
       <label for="id_first_name">First name:</label>
       <input id="id_first_name" type="text" name="first_name"/>
     </p>
     <p>
       <label for="id_last_name">Last name:</label>
       <input id="id_last_name" type="text" name="last_name"/>
     </p>
     <p>
       <label for="id_username">Username:</label>
       <input id="id_username" type="text" name="username"/>
     </p>
     <p>
       <label for="id_password">Password:</label>
       <input id="id_password" type="password" name="password"/>
     </p>
     <p>
       <label for="id_email">Email:</label>
       <input id="id_email" type="email" name="email"/>
     </p>
     <p>
       <label for="id_user_type">Type:</label>
       <input id="id_user_type" type="text" name="user_type" value="admin"/>
     </p>
     <!--
     <input id="id_slug" type="hidden" name="slug" value="eelkdlelsldldkldslkhhjjjjjj"/>
-->

     <input type="submit" value="Register" />

</div>
{% endblock %}

gameapp/templates/registerDeveloper.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}
{% block content %}

<div class="container">
   <h2>Developer Registration</h2>

     <form action="/register/" method="post">
     {% csrf_token %}
     <p>
       <label for="id_first_name">First name:</label>
       <input id="id_first_name" type="text" name="first_name"/>
     </p>
     <p>
       <label for="id_last_name">Last name:</label>
       <input id="id_last_name" type="text" name="last_name"/>
     </p>
     <p>
       <label for="id_username">Username:</label>
       <input id="id_username" type="text" name="username" />
     </p>
     <p>
       <label for="id_password">Password:</label>
       <input id="id_password" type="password" name="password" required=""/>
     </p>
     <p>
       <label for="id_email">Email:</label>
       <input id="id_email" type="email" name="email" required="" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,63}$"/>
     </p>
     <p>
       <label for="id_user_type">Type:</label>
       <input id="id_user_type" type="text" name="user_type" value="developer"/>
     </p>

     <!--
     <input id="id_slug" type="hidden" name="slug" value="poo"/>
   -->

     <input type="submit" value="Register" />

</div>
{% endblock %}

gameapp/templates/search.html
{% extends "base.html" %}
{% block title %}{{page_title}}{% endblock %}
{% block content %}
{% load static %}

<div class="container">
  {% if games %}
    <div id="products" class="row">
      {% for game in games %}
        <div class="item col-xs-12 col-sm-4 col-lg-4">
            <div class="thumbnail">
                <img class="group list-group-image" src="{{ game.banner_url }}" alt="no image" />
                <div class="caption">
                    <h4 class="group inner list-group-item-heading"><a href="{{BASE_URL}}/game/{{ game.slug }}">{{ game.title }}</a></h4>
                    {# <p class="group inner list-group-item-text">{{game.desc|truncatechars:100}}</p>#}
                    {% if not game.bought %}
                    <div class="row">
                        <div class="col-xs-6">
                            <p class="lead">€ {{ game.price }}</p>
                        </div>
                        <div class="col-xs-6 text-right">
                            <a class="btn btn-success" href="http://www.jquery2dotnet.com">Buy</a>
                        </div>
                    </div>
                    {% else %}
                    <div class="row">
                        <div class="col-xs-6">
                        </div>
                        <div class="col-xs-6 text-right">
                            <a class="btn btn-success" href="{{BASE_URL}}/game/{{ game.slug }}">Play</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
      {% endfor %}
    </div>
    {% include "games_pagination.html" with search=search_string %}
  {% else %}
  <div class="well well-lg">Too bad we have no {{page_title}} yet </div>
  {% endif %}
</div>
{% endblock %}